// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_restlessshores' as 'L1.JS' 
export default L1 =
[
	[

	],
	[

	],
	[

	],
	[
"./dungeon_restlessshores/MAP_L1_Y003_X003.PNG", "./dungeon_restlessshores/MAP_L1_Y003_X004.PNG", "./dungeon_restlessshores/MAP_L1_Y003_X002.PNG", "./dungeon_restlessshores/MAP_L1_Y003_X005.PNG",
	],
	[
"./dungeon_restlessshores/MAP_L1_Y004_X003.PNG", "./dungeon_restlessshores/MAP_L1_Y004_X004.PNG", "./dungeon_restlessshores/MAP_L1_Y004_X002.PNG", "./dungeon_restlessshores/MAP_L1_Y004_X005.PNG",
	],
	[
"./dungeon_restlessshores/MAP_L1_Y005_X003.PNG", "./dungeon_restlessshores/MAP_L1_Y005_X002.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
