// Javascript Module by Dave Inchy:
// Source map for layer '2' in 'dungeon_restlessshores' as 'L2.JS' 
export default L2 =
[
	[

	],
	[

	],
	[
"./dungeon_restlessshores/MAP_L2_Y002_X002.PNG", "./dungeon_restlessshores/MAP_L2_Y002_X004.PNG",
	],
	[

	],
	[
"./dungeon_restlessshores/MAP_L2_Y004_X002.PNG", "./dungeon_restlessshores/MAP_L2_Y004_X004.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
