// Javascript Module by Dave Inchy:
// Source map for layer '3' in 'dungeon_windsward' as 'L3.JS' 
export default L3 =
[
	[
"./dungeon_windsward/MAP_L3_Y000_X000.PNG", "./dungeon_windsward/MAP_L3_Y000_X004.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./dungeon_windsward/MAP_L3_Y004_X000.PNG", "./dungeon_windsward/MAP_L3_Y004_X004.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
