// Javascript Module by Dave Inchy:
// Source map for layer '2' in 'outpostrush' as 'L2.JS' 
export default L2 =
[
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./outpostrush/MAP_L2_Y040_X004.PNG", "./outpostrush/MAP_L2_Y040_X002.PNG", "./outpostrush/MAP_L2_Y040_X000.PNG", "./outpostrush/MAP_L2_Y040_X006.PNG",
	],
	[

	],
	[
"./outpostrush/MAP_L2_Y042_X004.PNG", "./outpostrush/MAP_L2_Y042_X002.PNG", "./outpostrush/MAP_L2_Y042_X006.PNG", "./outpostrush/MAP_L2_Y042_X000.PNG",
	],
	[

	],
	[
"./outpostrush/MAP_L2_Y044_X004.PNG", "./outpostrush/MAP_L2_Y044_X002.PNG", "./outpostrush/MAP_L2_Y044_X000.PNG", "./outpostrush/MAP_L2_Y044_X006.PNG",
	],
	[

	],
	[
"./outpostrush/MAP_L2_Y046_X000.PNG", "./outpostrush/MAP_L2_Y046_X002.PNG", "./outpostrush/MAP_L2_Y046_X004.PNG", "./outpostrush/MAP_L2_Y046_X006.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
