// Javascript Module by Dave Inchy:
// Source map for layer '3' in 'outpostrush' as 'L3.JS' 
export default L3 =
[
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./outpostrush/MAP_L3_Y040_X004.PNG", "./outpostrush/MAP_L3_Y040_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./outpostrush/MAP_L3_Y044_X004.PNG", "./outpostrush/MAP_L3_Y044_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
