// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_windsward' as 'L1.JS' 
export default L1 =
[
	[

	],
	[

	],
	[
"./dungeon_windsward/MAP_L1_Y002_X003.PNG", "./dungeon_windsward/MAP_L1_Y002_X002.PNG", "./dungeon_windsward/MAP_L1_Y002_X004.PNG",
	],
	[
"./dungeon_windsward/MAP_L1_Y003_X003.PNG", "./dungeon_windsward/MAP_L1_Y003_X002.PNG", "./dungeon_windsward/MAP_L1_Y003_X004.PNG",
	],
	[
"./dungeon_windsward/MAP_L1_Y004_X003.PNG", "./dungeon_windsward/MAP_L1_Y004_X004.PNG",
	],
	[
"./dungeon_windsward/MAP_L1_Y005_X004.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
