// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'outpostrush' as 'L1.JS' 
export default L1 =
[
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./outpostrush/MAP_L1_Y040_X004.PNG", "./outpostrush/MAP_L1_Y040_X000.PNG", "./outpostrush/MAP_L1_Y040_X002.PNG", "./outpostrush/MAP_L1_Y040_X003.PNG", "./outpostrush/MAP_L1_Y040_X005.PNG", "./outpostrush/MAP_L1_Y040_X006.PNG", "./outpostrush/MAP_L1_Y040_X007.PNG",
	],
	[
"./outpostrush/MAP_L1_Y041_X004.PNG", "./outpostrush/MAP_L1_Y041_X005.PNG", "./outpostrush/MAP_L1_Y041_X003.PNG", "./outpostrush/MAP_L1_Y041_X001.PNG", "./outpostrush/MAP_L1_Y041_X002.PNG", "./outpostrush/MAP_L1_Y041_X006.PNG", "./outpostrush/MAP_L1_Y041_X007.PNG",
	],
	[
"./outpostrush/MAP_L1_Y042_X005.PNG", "./outpostrush/MAP_L1_Y042_X004.PNG", "./outpostrush/MAP_L1_Y042_X003.PNG", "./outpostrush/MAP_L1_Y042_X006.PNG", "./outpostrush/MAP_L1_Y042_X000.PNG", "./outpostrush/MAP_L1_Y042_X001.PNG", "./outpostrush/MAP_L1_Y042_X002.PNG", "./outpostrush/MAP_L1_Y042_X007.PNG",
	],
	[
"./outpostrush/MAP_L1_Y043_X005.PNG", "./outpostrush/MAP_L1_Y043_X004.PNG", "./outpostrush/MAP_L1_Y043_X003.PNG", "./outpostrush/MAP_L1_Y043_X006.PNG", "./outpostrush/MAP_L1_Y043_X000.PNG", "./outpostrush/MAP_L1_Y043_X001.PNG", "./outpostrush/MAP_L1_Y043_X002.PNG", "./outpostrush/MAP_L1_Y043_X007.PNG",
	],
	[
"./outpostrush/MAP_L1_Y044_X004.PNG", "./outpostrush/MAP_L1_Y044_X005.PNG", "./outpostrush/MAP_L1_Y044_X003.PNG", "./outpostrush/MAP_L1_Y044_X007.PNG", "./outpostrush/MAP_L1_Y044_X006.PNG",
	],
	[
"./outpostrush/MAP_L1_Y045_X005.PNG", "./outpostrush/MAP_L1_Y045_X004.PNG", "./outpostrush/MAP_L1_Y045_X001.PNG", "./outpostrush/MAP_L1_Y045_X002.PNG", "./outpostrush/MAP_L1_Y045_X003.PNG", "./outpostrush/MAP_L1_Y045_X006.PNG", "./outpostrush/MAP_L1_Y045_X007.PNG", "./outpostrush/MAP_L1_Y045_X000.PNG",
	],
	[
"./outpostrush/MAP_L1_Y046_X001.PNG", "./outpostrush/MAP_L1_Y046_X002.PNG", "./outpostrush/MAP_L1_Y046_X005.PNG", "./outpostrush/MAP_L1_Y046_X006.PNG", "./outpostrush/MAP_L1_Y046_X007.PNG",
	],
	[
"./outpostrush/MAP_L1_Y047_X000.PNG", "./outpostrush/MAP_L1_Y047_X002.PNG", "./outpostrush/MAP_L1_Y047_X005.PNG", "./outpostrush/MAP_L1_Y047_X006.PNG", "./outpostrush/MAP_L1_Y047_X007.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
