// Javascript Module by Dave Inchy:
// Source map for layer '4' in 'outpostrush' as 'L4.JS' 
export default L4 =
[
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./outpostrush/MAP_L4_Y040_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
