// Javascript Module by Dave Inchy:
// Source map for layer '7' in 'outpostrush' as 'L7.JS' 
export default L7 =
[
	[
"./outpostrush/MAP_L7_Y000_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
