// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_edengrove' as 'L1.JS' 
export default L1 =
[
	[

	],
	[

	],
	[

	],
	[
"./dungeon_edengrove/MAP_L1_Y003_X001.PNG", "./dungeon_edengrove/MAP_L1_Y003_X002.PNG",
	],
	[
"./dungeon_edengrove/MAP_L1_Y004_X002.PNG", "./dungeon_edengrove/MAP_L1_Y004_X001.PNG", "./dungeon_edengrove/MAP_L1_Y004_X003.PNG",
	],
	[
"./dungeon_edengrove/MAP_L1_Y005_X002.PNG", "./dungeon_edengrove/MAP_L1_Y005_X003.PNG", "./dungeon_edengrove/MAP_L1_Y005_X001.PNG",
	],
	[
"./dungeon_edengrove/MAP_L1_Y006_X002.PNG", "./dungeon_edengrove/MAP_L1_Y006_X003.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
