// Javascript Module by Dave Inchy:
// Source map for layer '2' in 'dungeon_edengrove' as 'L2.JS' 
export default L2 =
[
	[

	],
	[

	],
	[
"./dungeon_edengrove/MAP_L2_Y002_X000.PNG", "./dungeon_edengrove/MAP_L2_Y002_X002.PNG",
	],
	[

	],
	[
"./dungeon_edengrove/MAP_L2_Y004_X002.PNG", "./dungeon_edengrove/MAP_L2_Y004_X000.PNG",
	],
	[

	],
	[
"./dungeon_edengrove/MAP_L2_Y006_X002.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
