// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_shattermtn' as 'L1.JS' 
export default L1 =
[
	[

	],
	[
"./dungeon_shattermtn/MAP_L1_Y001_X002.PNG", "./dungeon_shattermtn/MAP_L1_Y001_X001.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y002_X002.PNG", "./dungeon_shattermtn/MAP_L1_Y002_X003.PNG", "./dungeon_shattermtn/MAP_L1_Y002_X001.PNG", "./dungeon_shattermtn/MAP_L1_Y002_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y002_X006.PNG", "./dungeon_shattermtn/MAP_L1_Y002_X005.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y003_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y003_X005.PNG", "./dungeon_shattermtn/MAP_L1_Y003_X003.PNG", "./dungeon_shattermtn/MAP_L1_Y003_X002.PNG", "./dungeon_shattermtn/MAP_L1_Y003_X006.PNG", "./dungeon_shattermtn/MAP_L1_Y003_X001.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y004_X005.PNG", "./dungeon_shattermtn/MAP_L1_Y004_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y004_X006.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y005_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y005_X005.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y006_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y006_X007.PNG", "./dungeon_shattermtn/MAP_L1_Y006_X006.PNG", "./dungeon_shattermtn/MAP_L1_Y006_X003.PNG",
	],
	[
"./dungeon_shattermtn/MAP_L1_Y007_X004.PNG", "./dungeon_shattermtn/MAP_L1_Y007_X007.PNG", "./dungeon_shattermtn/MAP_L1_Y007_X006.PNG", "./dungeon_shattermtn/MAP_L1_Y007_X003.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
