// Javascript Module by Dave Inchy:
// Source map for layer '2' in 'dungeon_shattermtn' as 'L2.JS' 
export default L2 =
[
	[
"./dungeon_shattermtn/MAP_L2_Y000_X002.PNG", "./dungeon_shattermtn/MAP_L2_Y000_X000.PNG",
	],
	[

	],
	[
"./dungeon_shattermtn/MAP_L2_Y002_X002.PNG", "./dungeon_shattermtn/MAP_L2_Y002_X004.PNG", "./dungeon_shattermtn/MAP_L2_Y002_X000.PNG", "./dungeon_shattermtn/MAP_L2_Y002_X006.PNG",
	],
	[

	],
	[
"./dungeon_shattermtn/MAP_L2_Y004_X004.PNG", "./dungeon_shattermtn/MAP_L2_Y004_X006.PNG",
	],
	[

	],
	[
"./dungeon_shattermtn/MAP_L2_Y006_X006.PNG", "./dungeon_shattermtn/MAP_L2_Y006_X004.PNG", "./dungeon_shattermtn/MAP_L2_Y006_X002.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
