// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_everfall' as 'L1.JS' 
export default L1 =
[
	[

	],
	[
"./dungeon_everfall/MAP_L1_Y001_X002.PNG", "./dungeon_everfall/MAP_L1_Y001_X001.PNG", "./dungeon_everfall/MAP_L1_Y001_X003.PNG",
	],
	[
"./dungeon_everfall/MAP_L1_Y002_X003.PNG", "./dungeon_everfall/MAP_L1_Y002_X001.PNG", "./dungeon_everfall/MAP_L1_Y002_X002.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
