// Javascript Module by Dave Inchy:
// Source map for layer '3' in 'newworld_vitaeeterna/L3' as 'L3.JS' 
export default L3 =
[
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y000_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y000_X052.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y004_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y004_X020.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y008_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y008_X004.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y012_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y012_X012.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y016_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y016_X012.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y020_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y020_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y024_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y024_X020.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y028_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y028_X024.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y032_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y032_X024.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y036_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y036_X052.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y040_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y040_X052.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y044_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y044_X052.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y048_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X048.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y048_X052.PNG",
	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L3/MAP_L3_Y052_X000.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X004.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X008.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X012.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X016.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X020.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X024.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X028.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X052.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X044.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X032.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X036.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X040.PNG", "./newworld_vitaeeterna/L3/MAP_L3_Y052_X048.PNG",
	],
	[

	],
	[

	],
	[
	]
];
