// Javascript Module by Dave Inchy:
// Source map for layer '1' in 'dungeon_reekwater' as 'L1.JS' 
export default L1 =
[
	[

	],
	[

	],
	[
"./dungeon_reekwater/MAP_L1_Y002_X003.PNG", "./dungeon_reekwater/MAP_L1_Y002_X002.PNG",
	],
	[
"./dungeon_reekwater/MAP_L1_Y003_X003.PNG", "./dungeon_reekwater/MAP_L1_Y003_X002.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
