// Javascript Module by Dave Inchy:
// Source map for layer '4' in 'newworld_vitaeeterna/L4' as 'L4.JS' 
export default L4 =
[
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y000_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X008.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X048.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y000_X016.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y008_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X016.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X048.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y008_X008.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y016_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X048.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X016.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y016_X008.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y024_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X048.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X008.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y024_X016.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y032_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X048.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X008.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y032_X016.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y040_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y040_X008.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y040_X016.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y040_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y040_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y040_X048.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L4/MAP_L4_Y048_X000.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X008.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X016.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X024.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X032.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X040.PNG", "./newworld_vitaeeterna/L4/MAP_L4_Y048_X048.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
