// Javascript Module by Dave Inchy:
// Source map for layer '6' in 'newworld_vitaeeterna/L6' as 'L6.JS' 
export default L6 =
[
	[
"./newworld_vitaeeterna/L6/MAP_L6_Y000_X032.PNG", "./newworld_vitaeeterna/L6/MAP_L6_Y000_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L6/MAP_L6_Y032_X032.PNG", "./newworld_vitaeeterna/L6/MAP_L6_Y032_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
