// Javascript Module by Dave Inchy:
// Source map for layer '5' in 'newworld_vitaeeterna/L5' as 'L5.JS' 
export default L5 =
[
	[
"./newworld_vitaeeterna/L5/MAP_L5_Y000_X032.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y000_X016.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y000_X048.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y000_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L5/MAP_L5_Y016_X032.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y016_X048.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y016_X016.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y016_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L5/MAP_L5_Y032_X032.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y032_X048.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y032_X016.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y032_X000.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
"./newworld_vitaeeterna/L5/MAP_L5_Y048_X000.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y048_X016.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y048_X032.PNG", "./newworld_vitaeeterna/L5/MAP_L5_Y048_X048.PNG",
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
	]
];
